# Generated by Django 4.2.2 on 2023-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0007_alter_cart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
