# Generated by Django 4.2.2 on 2023-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0010_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
